name: sprightly
description: Private, Free & Open Source Expense Manager.
version: 0.1.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # languages & internationalization
  applocale: ^1.0.2
  interpolation: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^0.1.3

  # hash creation
  crypto: ^2.1.3
  convert: ^2.1.1

  # path libraries
  path_provider: ^1.6.7
  path: 1.6.4

  # moor sqlite packages
  moor: ^2.4.2
  moor_ffi: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0
  build_runner: ^1.8.1

# need help, get from: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    # Mono fonts
    - family: PTMono
      fonts:
        - asset: assets/fonts/PT_Mono/PTMono-Regular.ttf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Regular.ttf
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Bold.ttf
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Italic.ttf
          style: italic
    # Regular fonts
    - family: Cousine
      fonts:
        - asset: assets/fonts/Cousine/Cousine-Regular.ttf
        - asset: assets/fonts/Cousine/Cousine-Bold.ttf
        - asset: assets/fonts/Cousine/Cousine-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Cousine/Cousine-Italic.ttf
          style: italic
    - family: Inika
      fonts:
        - asset: assets/fonts/Inika/Inika-Regular.ttf
        - asset: assets/fonts/Inika/Inika-Bold.ttf
    - family: Simonetta
      fonts:
        - asset: assets/fonts/Simonetta/Simonetta-Regular.ttf
        - asset: assets/fonts/Simonetta/Simonetta-Black.ttf
        - asset: assets/fonts/Simonetta/Simonetta-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Simonetta/Simonetta-Italic.ttf
          style: italic

  assets:
    - assets/queries_min/ # custom & complex sql queries
    - assets/i18n/ # internationalization (i18n) & language support
