name: sprightly
description: Private, Free & Open Source Expense Manager.
version: 0.1.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Functional programming
  dartz: ^0.9.1

  # Bloc for state management
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1

  # languages & internationalization
  applocale: ^1.0.3
  interpolation: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^0.1.3

  # cryptography
  crypto: ^2.1.4
  convert: ^2.1.1

  # path libraries
  path_provider: ^1.6.8
  path: 1.6.4

  # moor sqlite packages
  moor: ^3.1.0
  moor_ffi: ^0.6.0

  # package information
  package_info: 0.4.0+17

  # network access
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.10.0
  moor_generator: ^3.1.0
  english_words: ^3.1.5

# need help, get from: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    # Mono fonts
    - family: PTMono
      fonts:
        - asset: assets/fonts/PT_Mono/PTMono-Regular.ttf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Regular.ttf
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Bold.ttf
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Italic.ttf
          style: italic
    # Regular fonts
    - family: Cousine
      fonts:
        - asset: assets/fonts/Cousine/Cousine-Regular.ttf
        - asset: assets/fonts/Cousine/Cousine-Bold.ttf
        - asset: assets/fonts/Cousine/Cousine-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Cousine/Cousine-Italic.ttf
          style: italic
    - family: Inika
      fonts:
        - asset: assets/fonts/Inika/Inika-Regular.ttf
        - asset: assets/fonts/Inika/Inika-Bold.ttf
    - family: Simonetta
      fonts:
        - asset: assets/fonts/Simonetta/Simonetta-Regular.ttf
        - asset: assets/fonts/Simonetta/Simonetta-Black.ttf
        - asset: assets/fonts/Simonetta/Simonetta-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Simonetta/Simonetta-Italic.ttf
          style: italic

  assets:
    - assets/queries_min/ # custom & complex sql queries
    - assets/i18n/ # internationalization (i18n) & language support
